# Ubuntu 16.04.
sudo: required
dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libpthread-stubs0-dev
  - sudo apt-get install -y libstdc++6
  - |
    pushd /tmp
    wget -q http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    tar -xf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    cd clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04
    sudo cp -rf bin/ /usr/local/
    sudo cp -rf include/ /usr/local/
    sudo cp -rf lib /usr/local/
    sudo cp -rf libexec /usr/local/
    sudo cp -rf share /usr/local/
    popd

language: c++

matrix:
  include:
    - compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost PATH=/usr/local/bin:$PATH
    - compiler: g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env: COMPILER=g++-4.8 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost PATH=/usr/local/bin:$PATH
    - compiler: g++-4.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env: COMPILER=g++-4.7 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost PATH=/usr/local/bin:$PATH

script:
  - cd common && make -j4
  - cd ../unit-test && make test -j4

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - slxi1202@gmail.com
      - yaoyuannnn@gmail.com
