# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smaug/core/tensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from smaug.core import types_pb2 as smaug_dot_core_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='smaug/core/tensor.proto',
  package='smaug',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17smaug/core/tensor.proto\x12\x05smaug\x1a\x16smaug/core/types.proto\"V\n\x10TensorShapeProto\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x12!\n\x06layout\x18\x02 \x01(\x0e\x32\x11.smaug.DataLayout\x12\x11\n\talignment\x18\x03 \x01(\x05\"\xb7\x01\n\x0bTensorProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\tdata_type\x18\x02 \x01(\x0e\x32\x0f.smaug.DataType\x12&\n\x05shape\x18\x03 \x01(\x0b\x32\x17.smaug.TensorShapeProto\x12-\n\x0b\x64\x61ta_format\x18\x04 \x01(\x0e\x32\x18.smaug.DataStorageFormat\x12\x1f\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x11.smaug.TensorData\"\xa7\x01\n\nTensorData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\thalf_data\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nfloat_data\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0b\x64ouble_data\x18\x04 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x08int_data\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nint64_data\x18\x06 \x03(\x03\x42\x02\x10\x01\x12\x15\n\tbool_data\x18\x07 \x03(\x08\x42\x02\x10\x01\"8\n\x0fTensorDataArray\x12%\n\ndata_array\x18\x01 \x03(\x0b\x32\x11.smaug.TensorDatab\x06proto3'
  ,
  dependencies=[smaug_dot_core_dot_types__pb2.DESCRIPTOR,])




_TENSORSHAPEPROTO = _descriptor.Descriptor(
  name='TensorShapeProto',
  full_name='smaug.TensorShapeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dims', full_name='smaug.TensorShapeProto.dims', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layout', full_name='smaug.TensorShapeProto.layout', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alignment', full_name='smaug.TensorShapeProto.alignment', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=144,
)


_TENSORPROTO = _descriptor.Descriptor(
  name='TensorProto',
  full_name='smaug.TensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='smaug.TensorProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='smaug.TensorProto.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='smaug.TensorProto.shape', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='smaug.TensorProto.data_format', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='smaug.TensorProto.data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=330,
)


_TENSORDATA = _descriptor.Descriptor(
  name='TensorData',
  full_name='smaug.TensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='smaug.TensorData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='half_data', full_name='smaug.TensorData.half_data', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='smaug.TensorData.float_data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_data', full_name='smaug.TensorData.double_data', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='smaug.TensorData.int_data', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_data', full_name='smaug.TensorData.int64_data', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_data', full_name='smaug.TensorData.bool_data', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=500,
)


_TENSORDATAARRAY = _descriptor.Descriptor(
  name='TensorDataArray',
  full_name='smaug.TensorDataArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_array', full_name='smaug.TensorDataArray.data_array', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=558,
)

_TENSORSHAPEPROTO.fields_by_name['layout'].enum_type = smaug_dot_core_dot_types__pb2._DATALAYOUT
_TENSORPROTO.fields_by_name['data_type'].enum_type = smaug_dot_core_dot_types__pb2._DATATYPE
_TENSORPROTO.fields_by_name['shape'].message_type = _TENSORSHAPEPROTO
_TENSORPROTO.fields_by_name['data_format'].enum_type = smaug_dot_core_dot_types__pb2._DATASTORAGEFORMAT
_TENSORPROTO.fields_by_name['data'].message_type = _TENSORDATA
_TENSORDATAARRAY.fields_by_name['data_array'].message_type = _TENSORDATA
DESCRIPTOR.message_types_by_name['TensorShapeProto'] = _TENSORSHAPEPROTO
DESCRIPTOR.message_types_by_name['TensorProto'] = _TENSORPROTO
DESCRIPTOR.message_types_by_name['TensorData'] = _TENSORDATA
DESCRIPTOR.message_types_by_name['TensorDataArray'] = _TENSORDATAARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorShapeProto = _reflection.GeneratedProtocolMessageType('TensorShapeProto', (_message.Message,), {
  'DESCRIPTOR' : _TENSORSHAPEPROTO,
  '__module__' : 'smaug.core.tensor_pb2'
  # @@protoc_insertion_point(class_scope:smaug.TensorShapeProto)
  })
_sym_db.RegisterMessage(TensorShapeProto)

TensorProto = _reflection.GeneratedProtocolMessageType('TensorProto', (_message.Message,), {
  'DESCRIPTOR' : _TENSORPROTO,
  '__module__' : 'smaug.core.tensor_pb2'
  # @@protoc_insertion_point(class_scope:smaug.TensorProto)
  })
_sym_db.RegisterMessage(TensorProto)

TensorData = _reflection.GeneratedProtocolMessageType('TensorData', (_message.Message,), {
  'DESCRIPTOR' : _TENSORDATA,
  '__module__' : 'smaug.core.tensor_pb2'
  # @@protoc_insertion_point(class_scope:smaug.TensorData)
  })
_sym_db.RegisterMessage(TensorData)

TensorDataArray = _reflection.GeneratedProtocolMessageType('TensorDataArray', (_message.Message,), {
  'DESCRIPTOR' : _TENSORDATAARRAY,
  '__module__' : 'smaug.core.tensor_pb2'
  # @@protoc_insertion_point(class_scope:smaug.TensorDataArray)
  })
_sym_db.RegisterMessage(TensorDataArray)


_TENSORDATA.fields_by_name['half_data']._options = None
_TENSORDATA.fields_by_name['float_data']._options = None
_TENSORDATA.fields_by_name['double_data']._options = None
_TENSORDATA.fields_by_name['int_data']._options = None
_TENSORDATA.fields_by_name['int64_data']._options = None
_TENSORDATA.fields_by_name['bool_data']._options = None
# @@protoc_insertion_point(module_scope)
